#Department
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
#department
# Launch browser and login
driver = webdriver.Chrome()
driver.get("https://uat-macdata.amigo-products.com/app/login")
driver.maximize_window()
driver.find_element(By.XPATH, "//input[@id='email']").send_keys('admin@sanadi.com')
driver.find_element(By.XPATH, "//input[@id='password']").send_keys('Sanadi@123')
driver.find_element(By.XPATH, "//span[text()='Log in']").click()
time.sleep(4)
driver.find_element(By.XPATH, "//div[@aria-label='dropdown trigger']").click()
time.sleep(4)
driver.find_element(By.XPATH, "//span[text()='Testing Branch']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//img[@class='p-element menu-icon']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//span[text()='Master']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//span[normalize-space()='Department']").click()
time.sleep(3)

# driver.find_element(By.XPATH, "//span[normalize-space()='+ Add New']").click()
# time.sleep(3)
# driver.find_element(By.ID, "department_name").send_keys("dep")
# time.sleep(3)
# driver.find_element(By.XPATH, "//div[@class='flex flex-row justify-content-between align-items-center']//div//button[@class='p-element primary p-button p-component ng-star-inserted']").click()
# time.sleep(3)
# driver.find_element(By.XPATH, "//table[1]/tbody[1]/tr[1]/td[3]/div[1]/button[1]").click()
# time.sleep(3)
# driver.find_element(By.ID, "department_name").clear()
# time.sleep(3)
# driver.find_element(By.ID, "department_name").send_keys("dept")
# time.sleep(3)
# driver.find_element(By.XPATH, "//div[@class='flex flex-row justify-content-between align-items-center']//div//button[@class='p-element primary p-button p-component ng-star-inserted']").click()
# time.sleep(3)


driver.find_element(By.XPATH, "//table[1]/tbody[1]/tr[1]/td[3]/div[1]/button[2]").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@aria-label='Yes']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@label='Inactive']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@placeholder='Search keyword']").send_keys("dep")
time.sleep(3)
driver.find_element(By.XPATH, "//table[1]/tbody[1]/tr[1]/td[3]/div[1]/button[1]").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@label='Active']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@placeholder='Search keyword']").send_keys("tons4")
time.sleep(3)
driver.find_element(By.XPATH, "//button[@aria-label='Show Filter Menu']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@class='p-inputtext p-component p-element ng-star-inserted']").send_keys("cat-33")
time.sleep(3)
driver.find_element(By.XPATH, "//span[normalize-space()='Apply']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@class='p-element p-button-outlined secondary md:hidden lg:flex xl:flex p-button p-component']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@icon='pi pi-upload']").click()
time.sleep(300)

