# unit master
import sys
import os
import time
from selenium.webdriver.common.by import By
# this is the path to directory that contains login.py
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'Functions')))

from login import login
driver = login()
time.sleep(5)
driver.find_element(By.XPATH, "//span[text()='Master']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//span[normalize-space()='Unit Master']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//span[normalize-space()='+ Add New']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@id='unit']").send_keys("tons3")
time.sleep(3)
driver.find_element(By.XPATH, "//div[@class='flex flex-row justify-content-between align-items-center']//div//button[@class='p-element primary p-button p-component ng-star-inserted']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//table[1]/tbody[1]/tr[1]/td[2]/div[1]/button[1]").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@id='unit']").clear()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@id='unit']").send_keys("tons4")
time.sleep(3)
driver.find_element(By.XPATH, "//div[@class='flex flex-row justify-content-between align-items-center']//div//button[@class='p-element primary p-button p-component ng-star-inserted']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//tbody/tr[1]/td[2]/div[1]/button[2]").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@aria-label='Yes']").click()
time.sleep(3)

driver.find_element(By.XPATH, "//button[@label='Inactive']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@placeholder='Search keyword']").send_keys("tons4")
time.sleep(3)
driver.find_element(By.XPATH, "//table[1]/tbody[1]/tr[1]/td[2]/div[1]/button[1]/span[1]").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@label='Active']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@placeholder='Search keyword']").send_keys("tons4")
time.sleep(3)
driver.find_element(By.XPATH, "//button[@aria-label='Show Filter Menu']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//input[@class='p-inputtext p-component p-element ng-star-inserted']").send_keys("tons2")
time.sleep(3)
driver.find_element(By.XPATH, "//span[normalize-space()='Apply']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@class='p-element p-button-outlined secondary md:hidden lg:flex xl:flex p-button p-component']").click()
time.sleep(3)
driver.find_element(By.XPATH, "//button[@icon='pi pi-upload']").click()
time.sleep(300)

